<a href="https://colab.research.google.com/github/soup511/ML/blob/main/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=df.drop('species',axis=1)
y=df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
x, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn=KNeighborsClassifier(n_neighbors=5)

In [12]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
knn.score(X_test,y_test)

0.98

In [14]:
from sklearn.svm import SVC

In [16]:
svm=SVC(C=30,kernel='rbf',gamma='auto')

In [18]:
svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [19]:
svm.score(X_test,y_test)

0.98

grid search cv

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
classifier=GridSearchCV(svm,{'C':[1,10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False)

In [22]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [23]:
classifier.cv_results_

{'mean_fit_time': array([0.00475326, 0.00405502, 0.00406923, 0.00462132, 0.00896664,
        0.00382738, 0.00381222, 0.0041851 ]),
 'std_fit_time': array([0.00056095, 0.00013768, 0.00053515, 0.0015537 , 0.00824141,
        0.00042713, 0.00033864, 0.00014139]),
 'mean_score_time': array([0.0035049 , 0.00305791, 0.00300822, 0.00410719, 0.0055438 ,
        0.0028934 , 0.00291095, 0.00314589]),
 'std_score_time': array([0.00077459, 0.00016939, 0.00012905, 0.00238061, 0.00322162,
        0.00016722, 0.00018427, 0.00033206]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [24]:
result=pd.DataFrame(classifier.cv_results_)

In [25]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004753,0.000561,0.003505,0.000775,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.004055,0.000138,0.003058,0.000169,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.004069,0.000535,0.003008,0.000129,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.004621,0.001554,0.004107,0.002381,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.008967,0.008241,0.005544,0.003222,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.003827,0.000427,0.002893,0.000167,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.003812,0.000339,0.002911,0.000184,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.004185,0.000141,0.003146,0.000332,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf = RandomForestClassifier(random_state=42)
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, None],
    'criterion': ['gini', 'entropy']
}
classifier = GridSearchCV(rf, param_grid_rf, cv=5, return_train_score=False)

In [32]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [10, 20, None],
                         'n_estimators': [100, 200, 300]})

In [36]:
results = pd.DataFrame(classifier.cv_results_)[['param_n_estimators', 'param_max_depth', 'param_criterion', 'mean_test_score']]

In [39]:
results.sort_values(by='mean_test_score', ascending=False).head()

   param_n_estimators param_max_depth param_criterion  mean_test_score
0                 100              10            gini         0.966667
1                 200              10            gini         0.966667
2                 300              10            gini         0.966667
3                 100              20            gini         0.966667
4                 200              20            gini         0.966667